name: color_sprout
description: Tap the tiles until you create a pattern!

version: 1.1.2+6

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  flame: ^0.25.0
  shared_preferences: ^0.5.6+3
  url_launcher: ^5.5.0
  font_awesome_flutter: ^8.8.1

dev_dependencies:
  flutter_launcher_icons: ^0.7.3

  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  image_path: "assets/icon.png"

flutter:
  uses-material-design: true
