name: color_sprout
description: Tap the tiles until you create a pattern!

version: 1.1.3+8

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flame: ^1.16.0
  shared_preferences: ^2.2.2
  url_launcher: ^6.2.5
  font_awesome_flutter: ^10.7.0

dev_dependencies:
  flutter_launcher_icons: ^0.13.1

  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  image_path: "assets/icon.png"

flutter:
  uses-material-design: true
